# evaluate_and_visualize.py
#
# This script loads a pre-trained Pinpoint-Transformer model and evaluates it
# on a complete test dataset that may be scattered across multiple directories.
#
# TASKS:
# 1. Loads the specified model checkpoint.
# 2. Loads the test dataset from multiple source directories by dynamically finding all files.
# 3. Runs a full evaluation and prints a classification report and confusion matrix.
# 4. Iterates through every sample in the test set to generate and save:
#    - Cross-attention map visualizations.
#    - Grad-CAM comparison visualizations (Original vs. Standard vs. Multi-Layer).
#
# Author: AI Assistant
# Date: October 27, 2023
# ---------------------------------------------------------------------------------

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
import torchvision.transforms as transforms
from torchvision.transforms import v2 as T
import torchvision.models as models
import cv2
from sklearn.metrics import classification_report, confusion_matrix
import numpy as np
import json
import os
import random
import matplotlib.pyplot as plt
from tqdm import tqdm
import glob
import traceback
from collections import Counter

# =================================================================================
# 1. CONFIGURATION
# =================================================================================
# =================================================================================
# 1. CONFIGURATION (MODIFIED FOR NEW PREPROCESSING)
# =================================================================================
class Config:
    # --- Paths for this Evaluation Script ---
    # !!! IMPORTANT: UPDATE THESE PATHS !!!
    MODEL_PATH = "/kaggle/input/fav-pp-xai-first-model/best_pinpoint_model_antisocial.pth"

    # --- MODIFIED: Point to the new unified preprocessed data and metadata ---
    # This is the path to the folder containing your 'train', 'dev', and 'test' subdirectories.
    # Example: "/kaggle/working/preprocessed_data"
    DATA_DIRECTORY = "/kaggle/input/fav-pre-process/preprocessed_data"
    
    # This is the path to the single metadata file generated by your new script.
    # Example: "/kaggle/working/preprocessed_data/preprocessed_metadata_full_....json"
    METADATA_PATH = "/kaggle/input/fav-pre-process/preprocessed_data/preprocessed_metadata_test_only_20250908_142055.json"

    # Directory to save all generated images
    OUTPUT_VISUALS_DIR = "/kaggle/working/evaluation_outputs"

    # --- Evaluation Settings ---
    DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
    METRICS_BATCH_SIZE = 8
    VISUALIZATION_BATCH_SIZE = 1
    
    # --- Sample Count Controller ---
    # Set to None to use all samples, or specify a number for a quick run
    MAX_SAMPLES = None
    
    # --- Debugging Settings ---
    DEBUG_MODE = False
    RANDOMIZE_SAMPLES = True
    
    # --- Parameters from Training (MUST MATCH THE SAVED MODEL) ---
    # These values are taken from your new preprocessing script
    NUM_FRAMES = 64
    VIDEO_SIZE = (128, 128)
    NUM_MFCC = 13
    NORM_MEAN = [0.485, 0.456, 0.406]
    NORM_STD = [0.229, 0.224, 0.225]
    EMBED_DIM = 256
    NUM_HEADS = 8
    NUM_LAYERS = 3
    DROPOUT = 0.1
    MAX_OFFSET = 5  # These are part of the model definition and should match
    
config = Config()


# =================================================================================
# 2. HELPER/MODEL CLASSES (Unchanged)
# =================================================================================

class AddRandomNoise:
    def __init__(self, min_noise=0.01, max_noise=0.1):
        self.min_noise = min_noise
        self.max_noise = max_noise
    def __call__(self, tensor):
        noise_level = random.uniform(self.min_noise, self.max_noise)
        return tensor + torch.randn_like(tensor) * noise_level

class VideoFeatureExtractor(nn.Module):
    def __init__(self, embed_dim):
        super().__init__()
        resnet = models.resnet18(weights=None)
        modules = list(resnet.children())[:-2]
        self.feature_extractor = nn.Sequential(*modules)
        self.pool = nn.AdaptiveAvgPool2d((1, 1))
        self.projection = nn.Linear(resnet.fc.in_features, embed_dim)
    def forward(self, x):
        b, t, c, h, w = x.shape
        x = x.view(b * t, c, h, w)
        features = self.feature_extractor(x)
        pooled_features = self.pool(features).view(b * t, -1)
        projected_features = self.projection(pooled_features)
        output = projected_features.view(b, t, -1)
        return output

class AudioFeatureExtractor(nn.Module):
    def __init__(self, num_mfcc, embed_dim):
        super().__init__()
        self.conv1 = nn.Conv1d(in_channels=num_mfcc, out_channels=64, kernel_size=3, padding=1)
        self.conv2 = nn.Conv1d(in_channels=64, out_channels=128, kernel_size=3, padding=1)
        self.ln = nn.LayerNorm(128)
        self.gru = nn.GRU(input_size=128, hidden_size=embed_dim, batch_first=True)
    def forward(self, x):
        x = x.transpose(1, 2)
        x = F.relu(self.conv1(x))
        x = F.relu(self.conv2(x))
        x = x.transpose(1, 2)
        x = self.ln(x)
        output, _ = self.gru(x)
        return output

def get_sinusoidal_embeddings(n_position, d_hid):
    def get_position_angle_vec(position):
        return [position / np.power(10000, 2 * (hid_j // 2) / d_hid) for hid_j in range(d_hid)]
    sinusoid_table = np.array([get_position_angle_vec(pos_i) for pos_i in range(n_position)])
    sinusoid_table[:, 0::2] = np.sin(sinusoid_table[:, 0::2])
    sinusoid_table[:, 1::2] = np.cos(sinusoid_table[:, 1::2])
    return torch.FloatTensor(sinusoid_table).unsqueeze(0)

class GatedCrossAttentionBlock(nn.Module):
    def __init__(self, embed_dim, num_heads, dropout):
        super().__init__()
        self.ln1 = nn.LayerNorm(embed_dim)
        self.ln2 = nn.LayerNorm(embed_dim)
        self.audio_to_video_attn = nn.MultiheadAttention(embed_dim, num_heads, dropout=dropout, batch_first=True)
        self.gate = nn.Sequential(nn.Linear(embed_dim, embed_dim), nn.Sigmoid())
        self.self_attn = nn.MultiheadAttention(embed_dim, num_heads, dropout=dropout, batch_first=True)
        self.ffn = nn.Sequential(nn.Linear(embed_dim, embed_dim * 4), nn.GELU(), nn.Dropout(dropout), nn.Linear(embed_dim * 4, embed_dim))
        self.dropout = nn.Dropout(dropout)
    def forward(self, audio_feat, video_feat, video_mask=None):
        audio_norm = self.ln1(audio_feat)
        video_norm = self.ln1(video_feat)
        cross_attn_output, cross_attn_map = self.audio_to_video_attn(query=audio_norm, key=video_norm, value=video_norm, key_padding_mask=video_mask)
        audio_feat = audio_feat + self.dropout(cross_attn_output)
        gated_audio_feat = audio_feat * self.gate(audio_feat)
        gated_audio_norm = self.ln2(gated_audio_feat)
        self_attn_output, _ = self.self_attn(gated_audio_norm, gated_audio_norm, gated_audio_norm)
        gated_audio_feat = gated_audio_feat + self.dropout(self_attn_output)
        gated_audio_norm2 = self.ln2(gated_audio_feat)
        ffn_output = self.ffn(gated_audio_norm2)
        final_output = gated_audio_feat + self.dropout(ffn_output)
        return final_output, cross_attn_map

class PinpointTransformer(nn.Module):
    def __init__(self, config):
        super().__init__()
        self.config = config
        self.video_extractor = VideoFeatureExtractor(config.EMBED_DIM)
        self.audio_extractor = AudioFeatureExtractor(config.NUM_MFCC, config.EMBED_DIM)
        self.video_pos_encoder = nn.Parameter(torch.randn(1, config.NUM_FRAMES, config.EMBED_DIM))
        self.gated_attention_layers = nn.ModuleList([GatedCrossAttentionBlock(config.EMBED_DIM, config.NUM_HEADS, config.DROPOUT) for _ in range(config.NUM_LAYERS)])
        self.classification_head = nn.Linear(config.EMBED_DIM, 1)
        num_offset_classes = 2 * config.MAX_OFFSET + 1
        self.offset_head = nn.Linear(config.EMBED_DIM, num_offset_classes)
    def forward(self, video, audio, video_mask=None):
        video_feat = self.video_extractor(video)
        audio_feat = self.audio_extractor(audio)
        video_feat = video_feat + self.video_pos_encoder[:, :video_feat.size(1), :]
        audio_len = audio_feat.size(1)
        audio_pos_encoding = get_sinusoidal_embeddings(audio_len, self.config.EMBED_DIM).to(audio_feat.device)
        audio_feat = audio_feat + audio_pos_encoding
        last_attention_map = None
        for layer in self.gated_attention_layers:
            audio_feat, attention_map = layer(audio_feat, video_feat, video_mask)
            last_attention_map = attention_map
        pooled_output = audio_feat.mean(dim=1)
        classification_logits = self.classification_head(pooled_output)
        offset_logits = self.offset_head(pooled_output)
        return classification_logits, offset_logits, last_attention_map

# =================================================================================
# =================================================================================
# FINAL CORRECTED DATASET CLASS
# This version correctly infers labels from the 'n_fakes' key in the original metadata,
# matching the true structure of the LAV-DF dataset.
# =================================================================================
# =================================================================================
# DATASET CLASS (ADAPTED FOR UNIFIED METADATA)
# This version reads from the single metadata file produced by the new preprocessing script.
# =================================================================================
class LAVDFDataset(Dataset):
    def __init__(self, config, split='test'):
        self.config = config
        self.split = split
        self.samples = []
        
        print(f"--- Loading '{split}' data from unified metadata ---")

        # Step 1: Load the single, preprocessed metadata file
        if not os.path.exists(config.METADATA_PATH):
            raise FileNotFoundError(
                f"Unified metadata file not found at: {config.METADATA_PATH}\n"
                "Please run the new preprocessing script and ensure the path in Config is correct."
            )
            
        print(f"Loading metadata from: {config.METADATA_PATH}")
        with open(config.METADATA_PATH, 'r') as f:
            all_metadata = json.load(f)
            
        # Step 2: Filter the metadata for the desired split ('test')
        split_metadata = [item for item in all_metadata if item.get('split') == self.split]
        print(f"Found {len(split_metadata)} total entries for split '{self.split}' in the metadata.")
        
        # Step 3: Construct full paths and load samples
        for item in tqdm(split_metadata, desc=f"Verifying '{self.split}' split files"):
            # Paths in the unified metadata are relative to the data directory
            video_path = os.path.join(config.DATA_DIRECTORY, item['preprocessed_video_path'])
            audio_path = os.path.join(config.DATA_DIRECTORY, item['preprocessed_audio_path'])

            # Ensure the preprocessed files actually exist
            if os.path.exists(video_path) and os.path.exists(audio_path):
                is_fake = (item['label'] == 'fake')
                label_value = 1.0 if is_fake else 0.0
                self.samples.append({
                    "video_path": video_path,
                    "audio_path": audio_path,
                    "label": label_value,
                    "is_fake": is_fake,
                    "original_label": item['label'] # Keep for debugging/visualization
                })

        print(f"Successfully located and loaded {len(self.samples)} samples for the '{self.split}' split.")
        if not self.samples:
            raise ValueError(f"CRITICAL: No valid data samples found for the '{self.split}' split. Check paths.")
        
        # Step 4: Apply sample limit if specified (for quick testing)
        if self.config.MAX_SAMPLES is not None and len(self.samples) > self.config.MAX_SAMPLES:
            print(f"Limiting dataset to {self.config.MAX_SAMPLES} samples (from {len(self.samples)} total).")
            if self.config.RANDOMIZE_SAMPLES:
                print("Randomizing sample order for a more representative subset.")
                random.shuffle(self.samples)
            self.samples = self.samples[:self.config.MAX_SAMPLES]
            print(f"Now using {len(self.samples)} samples for evaluation.")

        self.normalize_transform = T.Normalize(mean=self.config.NORM_MEAN, std=self.config.NORM_STD)

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        try:
            sample_info = self.samples[idx]
            video_path = sample_info["video_path"]
            audio_path = sample_info["audio_path"]
    
            # Load video tensor (remains the same)
            video_tensor_uint8 = torch.load(video_path)
            video_tensor = video_tensor_uint8.to(torch.float32) / 255.0
    
            # --- START: ROBUST AUDIO TENSOR HANDLING FROM TRAINING SCRIPT ---
            audio_tensor = torch.load(audio_path)
            original_shape = audio_tensor.shape
    
            # Case 1: 3D tensor (e.g., [Features, Channels, Time] or [Channels, Features, Time])
            # This is the case that was causing your error.
            if audio_tensor.ndim == 3:
                if audio_tensor.shape[0] == self.config.NUM_MFCC:
                    audio_tensor = audio_tensor.mean(dim=1).transpose(0, 1)
                elif audio_tensor.shape[1] == self.config.NUM_MFCC:
                    audio_tensor = audio_tensor.mean(dim=0).transpose(0, 1)
                elif audio_tensor.shape[2] == self.config.NUM_MFCC:
                    audio_tensor = audio_tensor.mean(dim=1)
                else:
                    print(f"Warning: Unfixable 3D audio shape {original_shape} at {audio_path}. Skipping.")
                    return None # Return None for bad samples

            # Case 2: 2D tensor (might need transposing)
            elif audio_tensor.ndim == 2:
                if audio_tensor.shape[0] == self.config.NUM_MFCC:
                    audio_tensor = audio_tensor.transpose(0, 1)
                elif audio_tensor.shape[1] != self.config.NUM_MFCC:
                    print(f"Warning: Audio shape {original_shape} has incorrect MFCC count. Skipping.")
                    return None # Return None for bad samples
            
            # Case 3: Invalid number of dimensions
            else:
                print(f"Warning: Audio tensor has invalid dimensions {audio_tensor.ndim}. Skipping.")
                return None # Return None for bad samples
            # --- END: ROBUST AUDIO TENSOR HANDLING ---
    
            video_tensor = self.normalize_transform(video_tensor)
    
            return {
                "video": video_tensor, "audio": audio_tensor, "label": sample_info["label"],
                "is_fake": sample_info["is_fake"], "video_path": sample_info["video_path"],
                "original_label": sample_info["original_label"]
            }
    
        except Exception as e:
            print(f"Warning: Error loading sample at index {idx} ({self.samples[idx]['video_path']}): {e}")
            return None

def collate_fn(batch):
    batch = [b for b in batch if b is not None]
    if not batch: return None
    
    max_audio_len = max([b['audio'].shape[0] for b in batch])
    
    # Initialize lists for all data fields
    padded_videos, padded_audios, video_masks, video_paths = [], [], [], []
    labels, is_fakes, original_labels = [], [], []

    for item in batch:
        video = item['video']
        current_frames = video.shape[0]

        # Standardize video frame count to match model expectation
        if current_frames > config.NUM_FRAMES:
            indices = torch.linspace(0, current_frames - 1, config.NUM_FRAMES, dtype=torch.long)
            video = video[indices]
        elif current_frames < config.NUM_FRAMES:
            pad_frames = config.NUM_FRAMES - current_frames
            padding = torch.zeros(pad_frames, video.shape[1], video.shape[2], video.shape[3], dtype=video.dtype)
            video = torch.cat([video, padding], dim=0)
        
        padded_videos.append(video)
        
        # Audio padding
        audio = item['audio']
        pad_len = max_audio_len - audio.shape[0]
        padded_audio = F.pad(audio, (0, 0, 0, pad_len), "constant", 0)
        padded_audios.append(padded_audio)

        # Append other necessary data
        video_masks.append(torch.zeros(config.NUM_FRAMES, dtype=torch.bool)) # No masking during eval
        labels.append(item['label'])
        is_fakes.append(item['is_fake'])
        video_paths.append(item['video_path'])
        original_labels.append(item['original_label'])
        
    return {
        "video": torch.stack(padded_videos),
        "audio": torch.stack(padded_audios),
        "video_mask": torch.stack(video_masks),
        "label": torch.tensor(labels, dtype=torch.float32),
        "is_fake": torch.tensor(is_fakes, dtype=torch.bool),
        "video_path": video_paths,
        "original_label": original_labels
    }

# =================================================================================
# 3. CORE EVALUATION & VISUALIZATION FUNCTIONS (Unchanged)
# =================================================================================

def run_full_evaluation(model, dataloader, device, config=None):
    """Runs model on the entire test set and prints metrics."""
    print("\n" + "="*50)
    print("--- Starting Full Evaluation for Metrics ---")
    model.eval()
    all_labels, all_preds, all_probs = [], [], []
    all_paths = []
    
    with torch.no_grad():
        for batch in tqdm(dataloader, desc="Calculating Metrics"):
            if batch is None: continue
            video, audio, video_mask = batch['video'].to(device), batch['audio'].to(device), batch['video_mask'].to(device)
            labels = batch['label']
            paths = batch['video_path']
            
            with torch.amp.autocast('cuda'):
                cls_logits, _, _ = model(video, audio, video_mask)
            
            probs = torch.sigmoid(cls_logits).squeeze(1).cpu().numpy()
            preds = (probs > 0.5).astype(int)
            
            all_labels.extend(labels.numpy().astype(int))
            all_preds.extend(preds)
            all_probs.extend(probs)
            all_paths.extend(paths)
    
    print("\n--- Final Test Results ---")
    if not all_labels:
        print("Warning: No samples were evaluated. Cannot calculate metrics.")
        return
    
    report = classification_report(all_labels, all_preds, target_names=['Real (0)', 'Fake (1)'], zero_division=0)
    cm = confusion_matrix(all_labels, all_preds)
    print(f"Total Samples Tested: {len(all_labels)}")
    print("\n--- Classification Report ---")
    print(report)
    print("\n--- Confusion Matrix ---")
    print("        Predicted")
    print("       Real  Fake")
    print(f"Real   {cm[0,0]:<5} {cm[0,1]:<5}")
    print(f"Fake   {cm[1,0]:<5} {cm[1,1]:<5}")
    
    # DEBUG: Analysis of misclassified samples
    if config and config.DEBUG_MODE:
        print("\n--- DEBUG: Misclassification Analysis ---")
        
        # Find misclassified samples
        misclassified = []
        for i, (true_label, pred_label, prob, path) in enumerate(zip(all_labels, all_preds, all_probs, all_paths)):
            if true_label != pred_label:
                misclassified.append({
                    'idx': i,
                    'true_label': 'Real' if true_label == 0 else 'Fake',
                    'pred_label': 'Real' if pred_label == 0 else 'Fake',
                    'confidence': prob if pred_label == 1 else (1 - prob),
                    'filename': os.path.basename(path)
                })
        
        print(f"Total misclassified samples: {len(misclassified)}")
        
        if len(misclassified) > 0:
            print("\nFirst 10 misclassified samples:")
            for i, sample in enumerate(misclassified[:10]):
                print(f"  {i+1:2d}. {sample['filename']:<25} True: {sample['true_label']:<4} Pred: {sample['pred_label']:<4} Conf: {sample['confidence']:.3f}")
            
            # Analyze confidence distribution
            high_conf_errors = [s for s in misclassified if s['confidence'] > 0.9]
            print(f"\nHigh-confidence errors (>90%): {len(high_conf_errors)}")
            if high_conf_errors:
                print("High-confidence misclassifications:")
                for sample in high_conf_errors[:5]:
                    print(f"  {sample['filename']:<25} True: {sample['true_label']:<4} Pred: {sample['pred_label']:<4} Conf: {sample['confidence']:.3f}")
        
        # Check for patterns in correct predictions
        print(f"\nConfidence distribution for correct predictions:")
        correct_probs = [probs for true_label, pred_label, probs in zip(all_labels, all_preds, all_probs) if true_label == pred_label]
        if correct_probs:
            import numpy as np
            print(f"  Mean confidence: {np.mean(correct_probs):.3f}")
            print(f"  Min confidence: {np.min(correct_probs):.3f}")
            print(f"  Max confidence: {np.max(correct_probs):.3f}")
            print(f"  Std deviation: {np.std(correct_probs):.3f}")
        
        print("--- END DEBUG ---\n")
    
    print("="*50 + "\n")

def save_attention_map_for_sample(model, batch, device, output_path):
    """Generates and saves a single attention map visualization."""
    model.eval()
    video, audio, video_mask = batch['video'].to(device), batch['audio'].to(device), batch['video_mask'].to(device)
    label = "Fake" if batch['is_fake'][0] else "Real"
    with torch.no_grad():
        with torch.amp.autocast('cuda'):
            cls_logits, _, attention_map = model(video, audio, video_mask)
    pred_prob = torch.sigmoid(cls_logits).item()
    pred_label = "Fake" if pred_prob > 0.5 else "Real"
    avg_attention_map = attention_map.squeeze(0).cpu().numpy()
    fig, ax = plt.subplots(figsize=(8, 8))
    im = ax.imshow(avg_attention_map, cmap='viridis', aspect='auto')
    ax.set_xlabel("Video Frames")
    ax.set_ylabel("Audio Time Steps (MFCCs)")
    ax.set_title(f"Cross-Attention Map\nGT: {label} | Pred: {pred_label} ({pred_prob:.2f})")
    fig.colorbar(im, ax=ax)
    plt.tight_layout()
    plt.savefig(output_path)
    plt.close(fig)

def save_grad_cam_for_sample(model, dataset, sample_idx, device, output_path):
    """Generates and saves a single 3-panel Grad-CAM visualization."""
    original_sample_info = dataset.samples[sample_idx]
    original_video_uint8 = torch.load(original_sample_info['video_path'])
    processed_sample = dataset[sample_idx]
    if processed_sample is None: 
        print(f"Skipping Grad-CAM for sample {sample_idx} due to loading error.")
        return
    video_tensor_model = processed_sample['video']
    audio_tensor_model = processed_sample['audio']
    fig, axes = plt.subplots(1, 3, figsize=(15, 5))
    frame_idx = config.NUM_FRAMES // 2
    original_frame_np = original_video_uint8[frame_idx].permute(1, 2, 0).numpy()
    axes[0].imshow(original_frame_np)
    axes[0].set_title(f"Original Frame {frame_idx}")
    axes[0].axis('off')
    heatmap_standard = generate_grad_cam(model, video_tensor_model, audio_tensor_model, frame_idx, device)
    heatmap_standard_resized = cv2.resize(heatmap_standard, (original_frame_np.shape[1], original_frame_np.shape[0]))
    heatmap_color = cv2.applyColorMap((255 * heatmap_standard_resized).astype(np.uint8), cv2.COLORMAP_JET)
    superimposed_standard = cv2.addWeighted(original_frame_np, 0.6, heatmap_color, 0.4, 0)
    axes[1].imshow(cv2.cvtColor(superimposed_standard, cv2.COLOR_BGR2RGB))
    axes[1].set_title("Standard Grad-CAM")
    axes[1].axis('off')
    heatmap_multi = generate_multi_layer_grad_cam(model, video_tensor_model, audio_tensor_model, frame_idx, device)
    heatmap_multi_resized = cv2.resize(heatmap_multi, (original_frame_np.shape[1], original_frame_np.shape[0]))
    heatmap_color_multi = cv2.applyColorMap((255 * heatmap_multi_resized).astype(np.uint8), cv2.COLORMAP_JET)
    superimposed_multi = cv2.addWeighted(original_frame_np, 0.6, heatmap_color_multi, 0.4, 0)
    axes[2].imshow(cv2.cvtColor(superimposed_multi, cv2.COLOR_BGR2RGB))
    axes[2].set_title("Multi-Layer Grad-CAM (Enhanced)")
    axes[2].axis('off')
    base_filename = os.path.basename(original_sample_info['video_path']).replace('_video.pt', '')
    gt_label = "Fake" if processed_sample['is_fake'] else "Real"
    fig.suptitle(f"Grad-CAM: {base_filename} (Ground Truth: {gt_label})", fontsize=16)
    plt.tight_layout(rect=[0, 0.03, 1, 0.95])
    plt.savefig(output_path, dpi=100)
    plt.close(fig)


# =================================================================================
# 4. GRAD-CAM HELPERS (Unchanged)
# =================================================================================

def generate_grad_cam(model, video_tensor, actual_audio, target_frame_idx, device):
    model.eval()
    original_audio_training_state = model.audio_extractor.training
    model.audio_extractor.train()
    video_tensor = video_tensor.clone().detach().to(device).requires_grad_(True)
    audio_tensor = actual_audio.unsqueeze(0).to(device)
    feature_maps, gradients = [], []
    def save_feature_map(m, i, o): feature_maps.append(o)
    def save_gradient(m, g_in, g_out): 
        if g_out[0] is not None: gradients.append(g_out[0])
    target_layer = model.video_extractor.feature_extractor[7]
    handle_fw = target_layer.register_forward_hook(save_feature_map)
    handle_bw = target_layer.register_backward_hook(save_gradient)
    default_heatmap = np.zeros((config.VIDEO_SIZE[0], config.VIDEO_SIZE[1]), dtype=np.float32)
    try:
        with torch.enable_grad():
            cls_logits, _, _ = model(video_tensor.unsqueeze(0), audio_tensor)
        if not feature_maps:
            handle_fw.remove(); handle_bw.remove()
            model.audio_extractor.train(original_audio_training_state)
            return default_heatmap
        pred_class_score = torch.sigmoid(cls_logits).squeeze()
        model.zero_grad()
        pred_class_score.backward(retain_graph=False)
        handle_fw.remove(); handle_bw.remove()
        if not gradients:
            model.audio_extractor.train(original_audio_training_state)
            return default_heatmap
        B_f, C, H_f, W_f = feature_maps[0].shape
        num_frames = video_tensor.shape[0]
        frame_feat = feature_maps[0].view(num_frames, C, H_f, W_f)[target_frame_idx].detach()
        frame_grad = gradients[0].view(num_frames, C, H_f, W_f)[target_frame_idx].detach()
        pooled_gradients = torch.mean(frame_grad, dim=(1, 2))
        for i in range(C):
            frame_feat[i] *= pooled_gradients[i]
        heatmap = torch.mean(frame_feat, dim=0).cpu().numpy()
        heatmap = np.maximum(heatmap, 0)
        if np.max(heatmap) > 0: heatmap /= np.max(heatmap)
    except Exception:
        handle_fw.remove(); handle_bw.remove()
        model.audio_extractor.train(original_audio_training_state)
        return default_heatmap
    model.audio_extractor.train(original_audio_training_state)
    return heatmap

def generate_multi_layer_grad_cam(model, video_tensor, actual_audio, target_frame_idx, device):
    model.eval()
    original_audio_training_state = model.audio_extractor.training
    model.audio_extractor.train()
    video_tensor = video_tensor.clone().detach().to(device).requires_grad_(True)
    audio_tensor = actual_audio.unsqueeze(0).to(device)
    target_layers = [model.video_extractor.feature_extractor[6], model.video_extractor.feature_extractor[7]]
    all_feature_maps, all_gradients, handles = [], [], []
    def make_hook(layer_idx):
        def save_feature_map(m, i, o): all_feature_maps.append((layer_idx, o))
        def save_gradient(m, g_in, g_out): 
            if g_out[0] is not None: all_gradients.append((layer_idx, g_out[0]))
        return save_feature_map, save_gradient
    for i, layer in enumerate(target_layers):
        fw_hook, bw_hook = make_hook(i)
        handles.append(layer.register_forward_hook(fw_hook))
        handles.append(layer.register_backward_hook(bw_hook))
    default_heatmap = np.zeros((config.VIDEO_SIZE[0], config.VIDEO_SIZE[1]), dtype=np.float32)
    try:
        with torch.enable_grad():
            cls_logits, _, _ = model(video_tensor.unsqueeze(0), audio_tensor)
        pred_confidence = torch.sigmoid(cls_logits).squeeze()
        model.zero_grad()
        pred_confidence.backward()
        for handle in handles: handle.remove()
        if not all_feature_maps or not all_gradients:
            model.audio_extractor.train(original_audio_training_state)
            return default_heatmap
        combined_heatmap = None
        layer_weights = [0.3, 0.7]
        for layer_idx in range(len(target_layers)):
            layer_features = next((feat for l_idx, feat in all_feature_maps if l_idx == layer_idx), None)
            layer_grads = next((grad for l_idx, grad in all_gradients if l_idx == layer_idx), None)
            if layer_features is None or layer_grads is None: continue
            num_frames = video_tensor.shape[0]
            B_f, C, H_f, W_f = layer_features.shape
            frame_feat = layer_features.view(num_frames, C, H_f, W_f)[target_frame_idx].detach()
            frame_grad = layer_grads.view(num_frames, C, H_f, W_f)[target_frame_idx].detach()
            pooled_gradients = torch.mean(frame_grad, dim=(1, 2))
            for c in range(C):
                frame_feat[c] *= pooled_gradients[c]
            layer_heatmap = torch.mean(frame_feat, dim=0).cpu().numpy()
            layer_heatmap = np.maximum(layer_heatmap, 0)
            if layer_heatmap.shape != (config.VIDEO_SIZE[0], config.VIDEO_SIZE[1]):
                layer_heatmap = cv2.resize(layer_heatmap, (config.VIDEO_SIZE[1], config.VIDEO_SIZE[0]))
            if np.max(layer_heatmap) > 0: layer_heatmap /= np.max(layer_heatmap)
            if combined_heatmap is None:
                combined_heatmap = layer_weights[layer_idx] * layer_heatmap
            else:
                combined_heatmap += layer_weights[layer_idx] * layer_heatmap
        if combined_heatmap is None:
            model.audio_extractor.train(original_audio_training_state)
            return default_heatmap
        combined_heatmap = np.maximum(combined_heatmap, 0)
        if np.max(combined_heatmap) > 0: combined_heatmap /= np.max(combined_heatmap)
    except Exception:
        for handle in handles: handle.remove()
        model.audio_extractor.train(original_audio_training_state)
        return default_heatmap
    model.audio_extractor.train(original_audio_training_state)
    return combined_heatmap


# =================================================================================
# 5. MAIN EXECUTION BLOCK
# =================================================================================
# if __name__ == '__main__':
    print("--- Starting Evaluation & Visualization Script ---")
    print(f"Using device: {config.DEVICE}")
    print(f"Loading model from: {config.MODEL_PATH}")
    
    # Show sample limit configuration
    if config.MAX_SAMPLES is not None:
        print(f"Sample limit: {config.MAX_SAMPLES} samples (for testing)")
    else:
        print("Sample limit: No limit (using all available samples)")
    
    # for d in config.TEST_DATA_DIRECTORIES:
    #     print(f" -> Will search for test data in: {d}")

    # --- Setup Output Directories ---
    attention_dir = os.path.join(config.OUTPUT_VISUALS_DIR, "attention_maps")
    gradcam_dir = os.path.join(config.OUTPUT_VISUALS_DIR, "grad_cam_visuals")
    os.makedirs(attention_dir, exist_ok=True)
    os.makedirs(gradcam_dir, exist_ok=True)
    print(f"Visualizations will be saved to: {config.OUTPUT_VISUALS_DIR}")

    # --- Load Model ---
    model = PinpointTransformer(config).to(config.DEVICE)
    try:
        model.load_state_dict(torch.load(config.MODEL_PATH, map_location=config.DEVICE))
        print("Model loaded successfully.")
    except Exception as e:
        print(f"FATAL: Could not load model. Error: {e}")
        exit()

    # --- Load Dataset ---
    try:
        test_dataset = LAVDFDataset(config, split='test')
        test_loader_metrics = DataLoader(test_dataset, batch_size=config.METRICS_BATCH_SIZE, shuffle=False, collate_fn=collate_fn, num_workers=2)
        test_loader_viz = DataLoader(test_dataset, batch_size=config.VISUALIZATION_BATCH_SIZE, shuffle=False, collate_fn=collate_fn, num_workers=2)
    except Exception as e:
        print(f"FATAL: Could not load dataset. Error: {e}")
        traceback.print_exc()
        exit()
        
    # --- STEP 1: Run Full Evaluation and Print Report ---
    run_full_evaluation(model, test_loader_metrics, config.DEVICE, config)
    
    # --- STEP 2: Generate and Save Visualizations for Every Sample ---
    print("\n" + "="*50)
    print("--- Starting Visualization Generation for Entire Test Set ---")
    print(f"Processing {len(test_dataset)} samples one by one...")

    model.eval()
    # We need the index to retrieve original file paths and for unique naming
    for i, batch in enumerate(tqdm(test_loader_viz, desc="Generating Visuals")):
        if batch is None:
            print(f"Warning: Skipping sample at index {i} due to a batching error.")
            continue
        
        try:
            # Get a unique filename for saving
            base_filename = os.path.basename(batch['video_path'][0]).replace('_video.pt', '')
            gt_label = "Fake" if batch['is_fake'][0] else "Real"
            
            # --- Generate and Save Attention Map ---
            attention_output_path = os.path.join(attention_dir, f"{i:04d}_{base_filename}_{gt_label}_attn.png")
            # This function runs with no_grad internally
            save_attention_map_for_sample(model, batch, config.DEVICE, attention_output_path)
        except Exception as e:
            print(f"\nError processing attention map for sample {i} ({base_filename}): {e}")
        
        try:
            base_filename = os.path.basename(batch['video_path'][0]).replace('_video.pt', '')
            gt_label = "Fake" if batch['is_fake'][0] else "Real"
            gradcam_output_path = os.path.join(gradcam_dir, f"{i:04d}_{base_filename}_{gt_label}_gradcam.png")
            # The Grad-CAM functions handle their own model.eval() and gradient contexts
            save_grad_cam_for_sample(model, test_dataset, i, config.DEVICE, gradcam_output_path)
        except Exception as e:
            print(f"\nError processing Grad-CAM for sample {i} ({base_filename}): {e}")
            traceback.print_exc()
    
    print("\n--- All tasks complete. ---")
    print(f"Evaluation metrics have been printed.")
    print(f"Visualizations saved in '{config.OUTPUT_VISUALS_DIR}'")